// export const CREATE_SERVER = 'CREATE_SERVER'
// export const UPDATE_SERVERS = 'UPDATE_SERVERS'
// export const FETCH_SERVERS = 'FETCH_SERVERS'

export enum ServerActionTypes {
  CREATE_SERVER = 'CREATE_SERVER',
  UPDATE_SERVERS = 'UPDATE_SERVERS',
  FETCH_SERVERS = 'FETCH_SERVERS'
}
